# -*- coding: utf-8 -*-

"""
trace/generated-tracers.rs
"""

__author__     = "Tanish Desai <tanishdesai37@gmail.com>"
__copyright__  = "Copyright 2025, Tanish Desai <tanishdesai37@gmail.com>"
__license__    = "GPL version 2 or (at your option) any later version"

__maintainer__ = "Stefan Hajnoczi"
__email__      = "stefanha@redhat.com"


from tracetool import out


def generate(events, backend, group):
    out('extern crate libc;')
    out('#[allow(unused_imports)]')
    out('use std::ffi::*;')
    out('use libc::{syslog, LOG_INFO};')
    out('#[inline(always)]',
        'fn trace_event_get_state_dynamic_by_id(_id: u16) -> bool {',
        '    unsafe { (trace_events_enabled_count != 0) && (_id != 0) }',
        '}',
        '',
        'const LOG_TRACE: u32 = 1 << 15;',
        'extern "C" {',
        '    static mut trace_events_enabled_count: u32;',
        '    static mut qemu_loglevel: u32;',
        '    pub fn qemu_log(fmt: *const libc::c_char, ...) -> ();'
        '}',)

    out('/* This file is autogenerated by tracetool, do not edit. */',
        '')

    out('extern "C" {')

    for e in events:
	    out('    static mut %s: u16;' % e.api(e.QEMU_DSTATE))
    out('}')

    # static state
    for e in events:
        if 'disable' in e.properties:
            enabled = 0
        else:
            enabled=1
        if "tcg-exec" in e.properties:
            # a single define for the two "sub-events"
            # a single define for the two "sub-events"
            out('const _TRACE_%(name)s_ENABLED: bool = %(enabled)s;',
                name=e.original.name.upper(),
				enabled="true" if (enabled==1) else "false")
        out('const _TRACE_%s_ENABLED: bool = %s;' % (e.name.upper(),"true" if ( enabled==1) else "false" ))

    backend.generate_begin(events, group)

    for e in events:
        if "disable" not in e.properties:
            cond = "(_TRACE_%s_ENABLED) && unsafe {trace_event_get_state_dynamic_by_id(_TRACE_%s_DSTATE)}" % (e.name.upper(),e.name.upper())
            out('',
			'#[inline(always)]',
            'pub fn %(api)s(%(args)s)',
            '{',
            '    if %(cond)s {',
            api=e.api(),
            args=e.rust_args,
            cond=cond)
            backend.generate(e, group)
            out('    }',
            '}')

    backend.generate_end(events, group)

